### ISSUE TITLE
Can't Build on VS 2017 Community

### ISSUE THREAD

**Issue by kirildi** [Youlean/Win32-Cairo-Build#1]
Hello. I'm not experienced programmer and also new in this plugins area, but want to try it.
Should mention that successfully build WDL-OL examples before, so not a total beginner( lol ).
I choose Iplug-Youlean, because it works with new versions of Visual Studio.
  
Anyway, so I tried to build a copy of IPlugExamples>IPlugEffect on VS Community 2015, but the error say to install some "Build tools v141", which I've found that it comes with VS Community 2017(not exactly). So VS 2015 was removed and I installed VS 2017(for kinda fresh start).
Then again I try to build IplugEffect and the new error was missing "YCAIRO\Cairo_Graphics\Lib-Win\cairo-win32-debug.lib"
I found this repo then and suppose that I should build the missing Cairo lib from here. 
So I download and copy the files from the instruction doc  and then start the Youlean_Win32_Cairo_Build.bat, but no success there.

VS path was wrong. New path on my laptop is 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community and the file is moved to 
Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
So I've changed it in Setup.bat the all passed, but then missing the Windows SDK 8.1. 
I've installed it then passed that step too, but again some files from the required libs and sdk haders and paths are missing again and still don't have luck building it.

**Comment by Youlean** [comment]
Hey, you can just use visual studio project for that. You should have asked first. :D
https://github.com/Youlean/IPlug-Youlean/tree/master/YCAIRO/Cairo_Graphics/projects

**Comment by kirildi** [comment]
Thank you for the quick support. I found that my Windows 10 SDK was new version (10.0.16299.0).
So after I change the "TargetPlatformVersion" in .vcxproj files in "/YCAIRO/Cairo_Graphics/projects" with it, build was successful.
The IPlugEffect build too. Thanks again,
